version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chess-online-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    image: chess-online-api:latest 
    container_name: chess_online_api_container
    restart: unless-stopped
    ports:
      - "8080:8080" 
    depends_on:
      - mysql 
    env_file:
      - .env
    networks: 
      - chess-online-network

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    image: chess-online-web:latest
    container_name: chess_online_web_container
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - chess-online-network

networks:
  chess-online-network:

volumes:
  mysql_data:
 