FROM node:22-alpine AS builder

WORKDIR /app

COPY web/chess-ui/package.json web/chess-ui/yarn.lock ./
RUN yarn install

COPY web/chess-ui/ .

RUN yarn build


FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]